video-site/meetingsvideos/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Landing.as_view(), name="landing_page"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("meetings/", views.MeetingsList.as_view(), name="meetings"),
    path("meetings/<slug:slug>/", views.MeetingDetail.as_view(), name="meeting_detail"),
    path("videos/<slug:slug>/", views.VideoDetail.as_view(), name="video_detail"),
    path("headings", views.HeadingsView.as_view(), name="headings"),
    path("headings/<slug:slug>/", views.HeadingDetail.as_view(), name="heading_detail"),
    path("symposia/", views.SymposiumList.as_view(), name="symposia"),
    path(
        "symposia/<slug:slug>/",
        views.SymposiumDetail.as_view(),
        name="symposium_detail",
    ),
    path("disciplines/", views.DisciplineList.as_view(), name="disciplines"),
    path(
        "disciplines/<slug:slug>/",
        views.DisciplineDetail.as_view(),
        name="discipline_detail",
    ),
    # path("departments/", views.DepartmentList.as_view(), name="departments"),
    # path(
    #     "departments/<slug:slug>/",
    #     views.DepartmentDetail.as_view(),
    #     name="department_detail",
    # ),
    path("speakers/", views.SpeakersView.as_view(), name="speakers"),
    path("speakers/<slug:slug>/", views.SpeakerDetail.as_view(), name="speaker_detail"),
    path("search/", views.search, name="search"),
    path("search_results/", views.search_results, name="search_results"),
    path(
        "search_results_advanced/",
        views.search_results_advanced,
        name="search_results_advanced",
    ),
]

video-site/meetingsvideos/models.py
from django.db import models
from django.db.models.functions import Substr
from autoslug import AutoSlugField

from locpy.api import LocEntity, NameEntity, SubjectEntity
import logging

logger = logging.getLogger(__name__)


class AlphaManager(models.Manager):
    """Custom manager to include first letter of LCSH heading, for use
    in creating faceted lists"""

    order_field = None

    def with_first_letter(self):
        return self.annotate(first_letter=Substr(self.order_field, 1, 1)).order_by(
            self.order_field
        )


class LCSHManager(AlphaManager):
    """Only return LCSH headings when used as subjects"""

    order_field = "heading"

    def only_topics(self):
        return self.filter(video__isnull=False).distinct()

    def only_topics_with_first_letter(self):
        first_queryset = self.with_first_letter()
        return first_queryset.filter(video__isnull=False).distinct()


class SpeakerManager(AlphaManager):
    order_field = "label"


class VideoManager(models.Manager):
    def exclude_inductions(self):
        """Do not return member inductions in queryset"""
        return self.exclude(admin_category="INDUCTION")


class LCSH(models.Model):
    heading = models.CharField(max_length=200)
    uri = models.CharField(max_length=200, blank=True, null=True)
    slug = AutoSlugField(populate_from="heading", unique=True)

    CATEGORY_CHOICES = {
        "PERSONAL_NAME": "Personal name",
        "CORPORATE_NAME": "Corporate name",
        "GEOGRAPHIC": "Geographic",
        "TOPIC": "Topic",
        "COMPLEX_SUBJECT": "Complex subject",
        "GENRE_FORM": "Genre/Form",
        "TITLE": "Title",
        "OTHER": "Other",
    }

    category = models.CharField(choices=CATEGORY_CHOICES, max_length=50)

    AUTHORITY_CHOICES = {
        "LOC": "LOC",
        "VIAF": "VIAF",
        "ORCID": "ORCID",
        "LOCAL": "Local",
        "OTHER": "Other",
    }

    authority = models.CharField(choices=AUTHORITY_CHOICES, max_length=50)

    components = models.ManyToManyField(
        "self", blank=True, symmetrical=False, related_name="component_of"
    )

    objects = LCSHManager()

    class Meta:
        verbose_name = "LCSH"
        verbose_name_plural = "LCSH"
        ordering = ["heading"]

    def __str__(self):
        return self.heading

    def without_dates(self):
        pass

    def save(self, **kwargs):
        # setting category as proxy for create vs update
        # make LOC subjects require lookup - change?
        if self.authority == "LOC" and not self.category:
            self.set_loc_data()
        super().save(**kwargs)
        # set components after save to avoid calling save method twice
        if self.category == "COMPLEX_SUBJECT" and not self.components.exists():
            self.get_components()

    @property
    def loc(self):
        uri = self.uri
        if uri.startswith("n"):
            entity = NameEntity(uri)
        elif uri.startswith("sh"):
            entity = SubjectEntity(uri)
        else:
            entity = LocEntity(uri)
        return entity

    def set_loc_data(self):
        category_mapping = {
            "http://www.loc.gov/mads/rdf/v1#PersonalName": "PERSONAL_NAME",
            "http://www.loc.gov/mads/rdf/v1#CorporateName": "CORPORATE_NAME",
            "http://www.loc.gov/mads/rdf/v1#Geographic": "GEOGRAPHIC",
            "http://www.loc.gov/mads/rdf/v1#Topic": "TOPIC",
            "http://www.loc.gov/mads/rdf/v1#ComplexSubject": "COMPLEX_SUBJECT",
            "http://www.loc.gov/mads/rdf/v1#Title": "TITLE",
            "http://www.loc.gov/mads/rdf/v1#GenreForm": "GENRE_FORM",
        }
        loc_entity = self.loc
        self.heading = str(loc_entity.authoritative_label)
        instances = [str(i) for i in loc_entity.instance_of]
        try:
            category = list(set(category_mapping.keys()).intersection(instances))[0]
            self.category = category_mapping[category]
        except IndexError:
            self.category = "OTHER"
            logger.warning(
                f"No matching instance found while setting LoC data for {self.uri}."
            )

    def get_components(self):
        loc_entity = self.loc
        for c in loc_entity.components:
            if isinstance(c, NameEntity) or isinstance(c, SubjectEntity):
                uri_stub = c.uri.split("/")[-1]
                component, _ = LCSH.objects.get_or_create(uri=uri_stub, authority="LOC")
                self.components.add(component)


class AcademicDiscipline(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True)

    def __str__(self):
        return self.name


class APSDepartment(models.Model):
    name = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from="name", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "APS department"


class Speaker(models.Model):
    display_name = models.CharField(
        max_length=200,
        help_text="The name as it would appear on a program, in order with no dates, e.g. 'Joyce Carol Oates'",
    )
    lcsh = models.ForeignKey(LCSH, blank=True, null=True, on_delete=models.SET_NULL)
    objects = SpeakerManager()
    label = models.CharField(max_length=200, blank=True, null=True)
    slug = AutoSlugField(populate_from="display_name", unique=True)

    def __str__(self):
        return self.label

    def save(self, **kwargs):
        self.display_name = self.display_name.strip()
        if self.lcsh and not self.label:
            self.label = self.lcsh.heading
        super().save(**kwargs)

    # TODO: if we want to keep using this, refactor to still work now that an affiliation can be associated with multiple meetings
    # def get_most_recent_affiliation(self):
    #     if len(self.affiliation_set.all()) > 0:
    #         return self.affiliation_set.all().order_by("-meeting")[0]
    #     else:
    #         return ""

    class Meta:
        ordering = ["label"]


class Affiliation(models.Model):
    speaker = models.ForeignKey(Speaker, on_delete=models.CASCADE)
    meetings = models.ManyToManyField("Meeting", blank=True)
    position = models.CharField(max_length=255, blank=True)
    institution = models.CharField(max_length=255, blank=True)

    def __str__(self):
        if self.position and self.institution:
            affiliation_str = f"{self.position}\n{self.institution}"
        else:
            affiliation_str = f"{self.position}{self.institution}"
        return affiliation_str


class WithNotes(models.Model):
    """
    Includes display_notes field (for additional text to display on the page
    for a given Meeting, Video, etc.) and admin_notes field (for information
    attached to a record that should NOT be displayed publicly)"""

    display_notes = models.TextField(
        blank=True, help_text="Additional text to display publicly"
    )
    admin_notes = models.TextField(
        blank=True,
        help_text="Use to attach additional information to record that will NOT display publicly",
    )

    class Meta:
        abstract = True


class Meeting(WithNotes):
    display_date = models.CharField(
        max_length=20,
        help_text="Human-readable date, e.g. 'November 2023' or 'April 2025",
    )
    start_date = models.DateField("First day of meeting - month, day, and year")
    end_date = models.DateField("Last day of meeting - month, day, and year")
    url = models.URLField(
        help_text="If this meeting has a page on the APS website, link it here",
        blank=True,
    )
    slug = AutoSlugField(populate_from="display_date", unique=True)

    def videos_by_time(self):
        return self.video_set.all().order_by("date", "order_in_day")

    def videos_by_date(self, query_date):
        return self.video_set.filter(date=query_date).order_by("order_in_day")

    def __str__(self):
        return self.display_date

    class Meta:
        ordering = ["start_date"]


class ProgramInfo(WithNotes):
    title = models.CharField(max_length=200)
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from="title", unique=True)

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.title = self.title.strip()
        super().save(**kwargs)

    class Meta:
        abstract = True


class Symposium(ProgramInfo):
    moderators = models.ManyToManyField(Speaker, blank=True)
    date = models.DateField()

    def videos_by_time(self):
        return self.video_set.all().order_by("date", "order_in_day")

    class Meta:
        verbose_name_plural = "Symposia"
        ordering = ["-date"]


class Video(ProgramInfo):
    lecture_additional_info = models.CharField(
        blank=True,
        help_text="e.g. '__ Memorial Lecture' or 'Keynote Lecture'",
        max_length=255,
    )
    symposium = models.ForeignKey(
        Symposium, blank=True, null=True, on_delete=models.SET_NULL
    )
    date = models.DateField("Month, day, and year.")
    order_in_day = models.IntegerField(default=0)
    speakers = models.ManyToManyField(Speaker, blank=True)
    abstract = models.TextField(blank=True)
    lcsh = models.ManyToManyField(LCSH, blank=True)
    # TODO: add validation for this
    doi = models.CharField(blank=True, max_length=255)
    diglib_pid = models.IntegerField(blank=True, null=True, unique=True)
    service_file = models.URLField(blank=True, null=True)
    youtube_url = models.URLField(blank=True, null=True)

    ADMIN_CATEGORY_CHOICES = {
        "ARCHIVES": "APS Archives",
        "INDUCTION": "Member Induction",
        "AWARDS": "Presentation of Awards",
        "CONCERT": "Concert",
        "LECTURE": "Lecture",
        "CONVERSATION": "In Conversation",
        "PANEL": "Panel Discussion",
        "OTHER": "Other",
    }

    admin_category = models.CharField(choices=ADMIN_CATEGORY_CHOICES, max_length=50)

video-site/meetingsvideos/forms.py
from django import forms
from .models import APSDepartment, AcademicDiscipline, LCSH
from django.db.models import Count


class AdvancedSearchForm(forms.Form):
    title = forms.CharField(max_length=100, label="Title", required=False)
    abstract = forms.CharField(max_length=100, label="Abstract", required=False)
    speaker = forms.CharField(max_length=100, label="Speaker", required=False)
    subject = forms.CharField(max_length=100, label="Subject", required=False)
    discipline = forms.ModelMultipleChoiceField(
        label="Academic discipline",
        queryset=AcademicDiscipline.objects.all(),
        required=False,
    )
    department = forms.ModelMultipleChoiceField(
        label="APS department", queryset=APSDepartment.objects.all(), required=False
    )

    # ADMIN_CATEGORY_CHOICES = {
    #     "ARCHIVES": "APS Archives",
    #     "INDUCTION": "Member Induction",
    #     "AWARDS": "Presentation of Awards",
    #     "CONCERT": "Concert",
    #     "LECTURE": "Lecture",
    #     "CONVERSATION": "In Conversation",
    #     "PANEL": "Panel Discussion",
    #     "OTHER": "Other",
    # }
    ADMIN_CATEGORY_CHOICES = {
        "LECTURE": "Lectures and Panels",
        "CONCERT": "Concerts",
        "INDUCTION": "Member Inductions",
        "AWARDS": "Presentation of Awards",
        "OTHER": "Other",
    }
    category = forms.MultipleChoiceField(
        choices=ADMIN_CATEGORY_CHOICES,
        label="Video category",
        widget=forms.CheckboxSelectMultiple,
        initial=[value for value in ADMIN_CATEGORY_CHOICES],
        required=False,
    )

    start_date = forms.DateField(
        label="Start date",
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=["%Y-%m-%d"],
        required=False,
    )
    end_date = forms.DateField(
        label="End date",
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=["%Y-%m-%d"],
        required=False,
    )


class SubjectModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj[0] + " ({})".format(obj[1])

    def prepare_value(self, value):
        if value is not None:
            return value[0]
        return super().prepare_value(value)


class FacetForm(forms.Form):
    template_name = "meetingsvideos/facet-form.html"
    lcsh = SubjectModelChoiceField(
        queryset=None,
        required=False,
        label="Subject",
        widget=forms.Select(attrs={"class": "form-select"}),
        empty_label="Choose...",
    )
    discipline = SubjectModelChoiceField(
        queryset=None,
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
        empty_label="Choose...",
    )
    start = forms.IntegerField(
        min_value=2003,
        max_value=2025,
        required=False,
        widget=forms.NumberInput(attrs={"class": "form-select"}),
    )
    end = forms.IntegerField(
        min_value=2003,
        max_value=2025,
        required=False,
        widget=forms.NumberInput(attrs={"class": "form-select"}),
    )

    def __init__(self, object_list, *args, **kwargs):
        super().__init__(*args, **kwargs)

        sub_query = (
            LCSH.objects.filter(video__in=object_list)
            .annotate(n=Count("heading"))
            .values_list("heading", "n")
            .order_by("-n")[:20]
        )

        discipline_query = (
            AcademicDiscipline.objects.filter(video__in=object_list)
            .annotate(n=Count("name"))
            .values_list("name", "n")
            .order_by("-n")[:20]
        )

        self.fields["lcsh"].queryset = sub_query
        self.fields["discipline"].queryset = discipline_query

video-site/templates/meetingsvideos/discipline_detail.html
{% extends "meetingsvideos/base.html" %}

{% block title %}
APS Meetings Videos - {{ discipline.name }}
{% endblock %}

{% block main %}
<div class="container" id="video-container">
<h1>{{ discipline.name }}</h1>

{% for video in discipline.video_set.all %}
    {% include "meetingsvideos/video_preview.html" with show_dates=True %}
{% endfor %}
</div>
{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("disciplinesNav");
</script>
{% endblock %}

video-site/templates/meetingsvideos/disciplines.html
{% extends "meetingsvideos/base.html" %}

{% block title %}
APS Meetings Videos - Academic Disciplines
{% endblock %}

{% block main %}
<div class="container" id="video-container">
  <h1>Academic Disciplines</h1>
  <div id="headings-list">
    {% include "meetingsvideos/item-list.html" with topics=topics %}
  </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("disciplinesNav");
</script>
{% endblock %}

video-site/templates/meetingsvideos/faceting.html
<form class='facet-filter-panel' id="facetSubmit{{ breakpoint }}" method="GET">
  {{ form }}
  <button type="submit" class="btn btn-primary">Filter results</button>
</form>
{% comment %}
<form method="GET">
  <div class="form-floating">
    <select class="form-select subjectSelect" id="subjectSelect{{ breakpoint }}" name="lcsh" aria-label="Select a subject">
      <option selected>Choose...</option>
      {% for subject in subjects %}
      <option value="{{ subject.subject }}">{{ subject.subject }} ({{ subject.n }})</option>
      {% endfor %}
    </select>
    <label for="subjectSelect{{ breakpoint }}">Select a subject</label>
  </div>
  <div class="form-floating">
    <select class="form-select disciplineSelect" id="disciplineSelect{{ breakpoint }}" name="disipline" aria-label="Select a discipline">
      <option selected>Choose...</option>
      {% for discipline in disciplines %}
      <option value="{{ discipline.discipline}}">{{ discipline.discipline }} ({{ discipline.n }})</option>
      {% endfor %}
    </select>
    <label for="disciplineSelect{{ breakpoint }}">Select a discipline</label>
  </div>
  <div class="input-group">
    <input type="number" min="2003" max="2025" class="form-control" aria-label="Start year" name="start" placeholder="Start">
    <span class="input-group-text">→</span>
    <input type="number" min="2003" max="2025" class="form-control" aria-label="End year" name="end" placeholder="End">
  </div>
  <button type="submit" class="btn btn-primary">Filter results</button>
</form>
{% endcomment %}

video-site/templates/meetingsvideos/headings.html
{% extends "meetingsvideos/base.html" %}

{% block title %}
APS Meetings Videos - Subjects
{% endblock %}

{% block main %}
  <div class="container" id="video-container">
    <h1>Subject Headings</h1>
    <ul class="nav nav-tabs">
      <li class="nav-item nav-tab-link htmx-tab">
        <a class="nav-link active" aria-selected="true" hx-get="{% url 'headings' %}" hx-target="#headings-list" hx-push-url="true">All</a>
      </li>
      <li class="nav-item nav-tab-link htmx-tab">
        <a class="nav-link" aria-selected="false" hx-get="{% url 'headings' %}?q=TOPIC&q=COMPLEX_SUBJECT" hx-target="#headings-list" hx-push-url="true">Topics</a>
      </li>
      <li class="nav-item nav-tab-link htmx-tab">
        <a class="nav-link" aria-selected="false" hx-get="{% url 'headings' %}?q=PERSONAL_NAME&q=CORPORATE_NAME" hx-target="#headings-list" hx-push-url="true">Names</a>
      </li>
      <li class="nav-item nav-tab-link htmx-tab">
        <a class="nav-link" aria-selected="false" hx-get="{% url 'headings' %}?q=GEOGRAPHIC" hx-target="#headings-list" hx-push-url="true">Geographic</a>
      </li>
    </ul>
    <div id="headings-list">
      {% include "meetingsvideos/item-list.html" with topics=topics %}
    </div>
  </div>
{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("headingsNav");
</script>
{% endblock %}

video-site/templates/meetingsvideos/index.html
{% extends "meetingsvideos/base.html" %}

{% block title %}
APS Meetings Videos - Browse
{% endblock %}
{% block md_sidebar %}
<div class="facets">
  {% include "meetingsvideos/faceting.html" with breakpoint="md" %}
</div>
{% endblock %}

{% block sm_sidebar %}           
<div class="modal fade d-md-none" id="facetsModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="modalLabel">Filter results</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% include "meetingsvideos/faceting.html" with breakpoint="med" %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block main %}
<div class="container" id="video-container">
  {% include "meetingsvideos/video-list.html" with videos=videos %}
</div>
{% endblock %}
{% block large_sidebar %}
<div class="facets">
  {% include "meetingsvideos/faceting.html" with breakpoint="lg" %}
</div>
{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("videoNav");
</script>
{% endblock %}

video-site/templates/meetingsvideos/search_results.html
{% extends "meetingsvideos/base.html" %}

{% block title %}
APS Meetings Videos - Search Results
{% endblock %}

{% block main %}
<div class="container" id="video-container">
  <h1>Search Results For: {{ query }}</h1>
  <ul class="nav nav-tabs" id="nav-tabs">
    <li class="nav-item nav-tab-link">
      <a class="nav-link active" href="#videos">Videos</a>
    </li>
    <li class="nav-item nav-tab-link">
      <a class="nav-link" href="#speakers">Speakers</a>
    </li>
    <li class="nav-item nav-tab-link">
      <a class="nav-link" href="#subjects">Subjects</a>
    </li>
    </ul>
  <div class="search-content">
    <div class="tab-pane active" id="videos">
      <h3>Videos</h3>
      {% if videos %}
        {% for video in videos %}
          {% include "meetingsvideos/video_preview.html" with show_dates=True%}
        {% endfor %}
      {% else %}
        <p>No videos found.</p>
      {% endif %}
    </div>
    <div class="tab-pane" id="speakers">
      <h3>Speakers</h3>
      {% if speakers %}
        {% for speaker in speakers %}
          <p><a href="{% url 'speaker_detail' speaker.slug %}">{{ speaker.display_name }}</a></p>
        {% endfor %}
      {% else %}
        <p>No speakers found.</p>
      {% endif %}
    </div>
    <div class="tab-pane" id="subjects">
      <h3>Subjects</h3>
      {% if subjects %}
        {% for subject in subjects %}
          <p><a href="{% url 'heading_detail' subject.slug %}">{{ subject.heading }}</a></p>
        {% endfor %}
      {% else %}
        <p>No subjects found.</p>
      {% endif %}
    </div>
  </div>
{% comment %}
<h3>Videos</h3>

{% if videos %}

{% for video in videos %}
    {% include "meetingsvideos/video_preview.html" with show_dates=True%}
{% endfor %}

{% else %}

<p>No videos found.</p>

{% endif %}

<hr>


<h3>Speakers</h3>

{% if speakers %}

{% for speaker in speakers %}
    <p><a href="{% url 'speaker_detail' speaker.slug %}">{{ speaker.display_name }}</a></p>
{% endfor %}

{% else %}

<p>No speakers found.</p>

{% endif %}

<hr>


<h3>Subjects</h3>

{% if subjects %}

{% for subject in subjects %}
    <p><a href="{% url 'heading_detail' subject.slug %}">{{ subject.heading }}</a></p>
{% endfor %}

{% else %}

<p>No subjects found.</p>

{% endif %}


</div>
{% endcomment %}
{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("searchNav");
  jsFunctions.makeSearchTabs();
</script>
{% endblock %}

video-site/templates/meetingsvideos/symposia.html
{% extends "meetingsvideos/base.html" %}

{% block title %}
APS Meetings Videos - Symposia
{% endblock %}

{% block main %}
<div class="container" id="video-container">
  <div class="accordion" id="symposium-accordion">
    {% include "meetingsvideos/symposium-list.html" %}
  </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("symposiaNav");
</script>
{% endblock %}

video-site/templates/meetingsvideos/video_detail.html
{% extends "meetingsvideos/base.html" %}
{% load static %}
{% load meetingsvideos_extras %} 

{% block title %}
  APS Meetings Videos - {{ video.title }}
{% endblock %}

{% block main %}
<link href="https://vjs.zencdn.net/8.23.3/video-js.css" rel="stylesheet" />

<div class="container" id="video-container">
  <div class="video-title">
    <h1>{{ video.title }}</h1>
  </div>
  {% if video.lecture_additional_info %}
  <h2>{{ video.lecture_additional_info }}</h2>
  {% endif %}
  <ul class="list-group speaker-list">
  {% for speaker in video.speakers.all %}
  <li class="list-group-item">
  <h3><a href="{% url 'speaker_detail' speaker.slug %}">{{ speaker.display_name }}</a></h3>
    {% for affiliation in speaker.affiliation_set|filter_affiliations:video.meeting %}
    {{ affiliation|linebreaks }}
    {% endfor %}
  </li>
  {% endfor %}
  </ul>

  <!--Set width and height in CSS and use media query for small breakpoints-->
  <video
    id="meeting-video"
    class="video-js vjs-16-9"
    controls
    preload="auto"
    poster="{% static 'images/aps-logo-mono.png' %}"
    data-setup='{}'
  >
    <source src="{{ video.service_file }}" type="video/mp4" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a>
    </p>
  </video>
<!--
<video width="320" height="240" controls>
    <source src="{{ video.service_file }}" type="video/mp4">
    <source src="{{ video.service_file }}" type="video/ogg">
  Your browser does not support the video tag.
</video>
-->

{% if video.display_notes %}
<p>{{ video.display_notes }}</p>
{% endif %}


<table class="table table-striped table-hover table-bordered" id="metadata-table">
  <tr>
    <td>Meeting</td>
    <td><a href="{% url 'meeting_detail' video.meeting.slug %}">{{ video.meeting }}</a></td>
  </tr>
  {% if video.abstract %}
  <tr>
    <td>Abstract</td>
    <td>{{ video.abstract }}</td>
  </tr>
  {% endif %}
  <tr>
    <td>Category</td>
    <td>{{ video.get_admin_category_display }}</td>
  </tr>
  {% if video.academic_disciplines.all %}
  <tr>
    <td><p>Academic Discipline</p></td>
    <td>
      {% for discipline in video.academic_disciplines.all %}
        <p><a href="{% url 'discipline_detail' discipline.slug %}">{{ discipline }}</a></p>
      {% endfor %}
    </td>
  </tr>
  {% endif %}
  <tr>
    <td><p>Subjects</p></td>
    <td>
      {% for heading in video.lcsh.all %}
        <p><a href="{% url 'heading_detail' heading.slug %}">{{ heading }}</a></p>
      {% endfor %}
    </td>
  </tr>
  {% comment %}
 {% if video.aps_departments.all %}
  <tr>
    <td>APS Department</td>
    <td>
      {% for department in video.aps_departments.all %}
        <p><a href="{% url 'department_detail' department.slug %}">{{ department }}</a></p>
      {% endfor %}</td>
  </tr>
  {% endif %}
  {% endcomment %}
</table>
{% if video.symposium %}
  <table class="table table-borderless">
    <tr>
      <td>Part of symposium:</td>
      <td><a href="{% url 'symposium_detail' video.symposium.slug %}">{{ video.symposium.title }}</a></td>
    </tr>
  {% if video.get_prev %}
    <tr>
      <td>Previous video:</td>
      <td><a href="{% url 'video_detail' video.get_prev.slug %}">{{ video.get_prev }}</a></td>
    </tr>
  {% endif %}

  {% if video.get_next %}
    <tr>
      <td>Next video:</td>
      <td><a href="{% url 'video_detail' video.get_next.slug %}">{{ video.get_next }}</a></td>
    </tr>
  {% endif %}
  </table>
  {% endif %}

</div>
<!-- TODO: these links don't work -->
<!-- <p><a href="https://diglib.amphilsoc.org/islandora/object/video:{{ video.diglib_pid }}">View in APS Digital Library</a></p> -->

{% endblock %}
{% block extra_js %}
<script>
  jsFunctions.makeActive("videoNav");
</script>
<script src="https://vjs.zencdn.net/8.23.3/video.min.js"></script>
{% endblock %}